name: GCP cloud functions deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          name: plant-info
          region: europe-central2
          source_dir: sprout_functions
          max_instances: 3
          runtime: go116
          credentials: ${{ secrets.gcp_credentials }}
